# Generated by Django 6.0.4 on 2026-04-29 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('COMIDA', 'Comida'), ('BEBIDA', 'Bebida')], max_length=20)),
                ('preparation_area', models.CharField(choices=[('COCINA', 'Cocina'), ('BAR', 'Bar'), ('CAJA', 'Caja'), ('ALMACEN', 'Almacen')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(default='pz', max_length=30)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area', models.CharField(choices=[('COCINA', 'Cocina'), ('BAR', 'Bar'), ('CAJA', 'Caja'), ('ALMACEN', 'Almacen')], default='ALMACEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('waiter_name', models.CharField(max_length=120)),
                ('guest_reference', models.CharField(blank=True, max_length=120)),
                ('request_scope', models.CharField(choices=[('MESA', 'Mesa completa'), ('COMENSAL', 'Por comensal')], default='MESA', max_length=20)),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diner_name', models.CharField(blank=True, max_length=120)),
                ('request_scope', models.CharField(choices=[('MESA', 'Mesa completa'), ('COMENSAL', 'Por comensal')], default='MESA', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('COMANDADO', 'Comandado'), ('EN_PREPARACION', 'En preparacion'), ('POR_ENTREGAR', 'Por entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='COMANDADO', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
