# Generated by Django 6.0.4 on 2026-04-30 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_preparation_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('COMANDADO', 'Comandado'), ('EN_PREPARACION', 'En preparación'), ('POR_ENTREGAR', 'Por entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='COMANDADO', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_supplies', to='core.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_products', to='core.supply')),
            ],
            options={
                'ordering': ['product__name', 'supply__name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplies',
            field=models.ManyToManyField(blank=True, related_name='products', through='core.ProductSupply', to='core.supply'),
        ),
        migrations.AddConstraint(
            model_name='productsupply',
            constraint=models.UniqueConstraint(fields=('product', 'supply'), name='unique_product_supply'),
        ),
    ]
