# Generated by Django 6.0.4 on 2026-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderitem_status_productsupply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='minimum_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
