# Generated by Django 6.0.4 on 2026-04-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variante_producto_supply_simplificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='unit',
        ),
    ]
