# Generated by Django 6.0.4 on 2026-04-30 01:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quitar_unit_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
