# Generated by Django 6.0.4 on 2026-04-30 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productvariant_price_delta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EMPLEADO', 'Empleado')], default='EMPLEADO', max_length=20)),
                ('can_menu', models.BooleanField(default=True)),
                ('can_administrador', models.BooleanField(default=False)),
                ('can_comanda', models.BooleanField(default=False)),
                ('can_cocina', models.BooleanField(default=False)),
                ('can_bar', models.BooleanField(default=False)),
                ('can_entregas', models.BooleanField(default=False)),
                ('can_caja', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso de usuario',
                'verbose_name_plural': 'Accesos de usuarios',
            },
        ),
    ]
