# Generated by Django 6.0.4 on 2026-04-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest_reference',
        ),
    ]
