# Generated by Django 6.0.4 on 2026-04-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_order_guest_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='waiter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
