# Generated by Django 6.0.4 on 2026-04-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderitem_waiter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='request_scope',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiter_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='request_scope',
        ),
    ]
