server {
    listen 80;
    server_name __SERVER_NAMES__;

    client_max_body_size 10M;

    location /static/ {
        alias __APP_DIR__/staticfiles/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
    }

    location /media/ {
        alias __APP_DIR__/media/;
        access_log off;
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:__GUNICORN_SOCKET__;
        proxy_read_timeout 120;
        proxy_connect_timeout 120;
        proxy_redirect off;
    }
}
