[program:__SERVICE_NAME__]
command=__APP_DIR__/deploy/gunicorn.sh
user=__SERVICE_USER__
autostart=true
autorestart=true
stdout_logfile=__LOGS_DIR__/out.log
stderr_logfile=__LOGS_DIR__/err.log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8
