[program:bar]
directory=/srv/bar/app
command=/bin/bash /srv/bar/app/deploy/gunicorn_start.sh
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/bar/supervisor-out.log
stderr_logfile=/var/log/bar/supervisor-err.log
environment=PYTHONUNBUFFERED="1"
